* Chapter 1 - The most basic of C++
Main purpose of this example is to demonstrate overall structure of a
C++ code, as well as some basic syntax. C++ is a compilation of many
other langauges. As such, it requires inclusion of additional
libraries or header files to do things like produce to standard
output..
** introduction and include files
- iostream defines input and output to cout / cin
- Sales item.h defines the sctructure of the Sales item object
- fstream defines I/O capabilities for a file type.
#+BEGIN_SRC C++
  #include <iostream>
  #include "Sales_item.h"
  #include <fstream>
#+END_SRC

** define the variable types you wish to use..
every c++ program needs to have some main() function
defined.. Remember that since this is some function, it must also have
some return type. Namely, 0.
#+BEGIN_SRC C++
    int main(){

      Sales_item item1, item2, item3;
      std::ifstream infile;
      std::string input1, input2;
      int count = 0;

#+END_SRC

** Get some user input to test data
example use of standard output and input. since input1 and input2 are
defined to be strings, cin will read whatever values input by the user
as a string type object..
#+BEGIN_SRC C++

      // prompt the user for some input
      std::cout << "Please indicate the file you would like to read " << std::endl;
      std::cin >> input1;

      // feel free to use "\n" as an alternative to std::endl
      std::cout << "Please indicate whether you want a total sum, or a specific ISBN" << "\n";
      std::cin >> input2;

#+END_SRC

** Implmentation of the user input
quick examples of if and while loops
- if (condition) { execute code }
  - else { execute other stuff }
- while (condition) { execute code }
#+BEGIN_SRC C++

// test to see if the input is the total
  if(input2 == "total"){
    infile.open(input1);

    // continue to read from the file while there is an item inside of it..
    while(infile >> item1){
      count++;
      std::cout << "The value of the sum at step: " << count << " is: ";
      item2 += item1;
      std::cout << item2 << "\n";
    }
   }

   // if the input is something else.. do this code instead..
   else if(input2 == "particular"){
     std::cout << "please input the particular isbn you want to check for: ";
     std::cin >> item2;
     infile.open(input1);
     while(infile >> item1){
       if(item2.isbn()==item1.isbn()){
         item3 += item1;
         count++;
       }
     }
     // print the thngs you read from the input..
     std::cout << "The the number of total transtions is: " << count << " total sales is: ";
     std::cout << item3 << "\n";
  
   }
  // if you don't get any of the things you hoped to read, this is an error!
   else{
     std::cerr << "input not correct \n";
     return -1;
   }
  infile.close();
#+END_SRC
don't forget to include your return type for the main function!
#+BEGIN_SRC C++
  return 0;
  }
#+END_SRC

