# set macro path
/control/macroPath macros/

#place the isotropic source, just outside the edge of the tranLoc
/gps/position 0 0 0 m

# set beam to emit optical photons
/gps/particle opticalphoton

#gps set the energy level
/gps/energy 2.5 eV

#make usre that the vizualation sees every separate run
#/vis/scene/endOfEventAction accumulate 1000

#create an isotropic source
/gps/ang/type iso

# set total number of events
/run/beamOn 10000
